### ISSUE TITLE
rename project to orthos

### ISSUE THREAD

**Issue by olafhering** [openSUSE/orthos2#108]
why is this thing called `orthosTwo` instead of just `orthos`?

Please  renamed it back to plain `orthos`, and do `git branch --move orthos1` in the old `orthos.git`.

**Comment by watologo1** [comment]
?!? orthos v1 never was public (internal gitlab repo).
orthos v2 is a major re-write. Using python-django instead of php for the web interface.

The public mainline git repo is already called orthos2:
https://github.com/openSUSE/orthos2
Reverting this is not an option.

**Comment by olafhering** [comment]
a git repo can be renamed in the webui.

**Comment by watologo1** [comment]
It's not only the app string in github or the package.
orthos2 may show up in quite some places.
I cannot see what is bad with making a total rewrite of an App, even using new programming language, at least for the whole web front-end by integrating this in the name.
While grub did the same, there are quite some re-names when things have been totally changed.

Why is it that important to keep the "orthos" naming?
It is on purpose that it is shown that it's  a new tool (with similar functionality).

**Comment by olafhering** [comment]
The various orthos2 strings can be renamed later.

It was SUSE who named the actual grub `grub2`, not upstream. And it was a bad move.

In case it will be rewritten once more in the future, would it be orthos3? Just name it what it is: orthos.

**Comment by SchoolGuy** [comment]
This project will be deprecated in the long term for a pure Cobbler setup with the new Cobbler-Web Web UI that is not specific to SUSE. As much as I am on the side of @olafhering I will not rename the project as it has greater implications in the current deployment workflow that is SUSE internal. The risk is too high.
