### ISSUE TITLE
Doc: describe machine setup dialogue in user guide

### ISSUE THREAD

**Issue by tamara-schmitz** [openSUSE/orthos2#147]
I still do not comprehend what the difference an install, install-auto, install-ssh etc. really is. If I did, I would improve the descripition in the user manual.

Please describe in the manual what each of these modes mean and how to use them. Say for some I have to SSH into the machine to complete the setup? That is very important knowledge.

**Comment by watologo1** [comment]
That has been integrated into the internal SUSE (gitlab) documentation a while ago. Thanks for reporting.
