### ISSUE TITLE
Make Orthos speak amqp (notification system, message bus)

### ISSUE THREAD

**Issue by jloeser** [openSUSE/orthos2#23]
Let's make Orthos capable of sending events that are happening in our app through a message bus using [AMQP](https://en.wikipedia.org/wiki/Advanced_Message_Queuing_Protocol) protocol. For Python there is [pika](https://pypi.org/project/pika/), a "pure-Python implementation of the AMQP 0-9-1 protocol including RabbitMQ’s extensions."

We already do it in a cumbersome way using these task models approach which does not comply to any protocol - its simple storing function names in Orthos database which later on gets read, removed (from database, its basically the queue) and called/executed by this [taskmanager](https://github.com/openSUSE/orthos2/blob/master/orthos2/taskmanager/executer.py).  

We could for example take [RabbitMQ](https://www.rabbitmq.com/) as our message broker (the system managing the queues etc.). RabbitMQ provides pub/sub functionality (https://www.rabbitmq.com/tutorials/tutorial-three-python.html) which would fit to our needs:

- A producer is a user application that sends messages.
- A queue is a buffer that stores messages.
- A consumer is a user application that receives messages.

There are also other types of queues and messages, including authentication system (who can read which queue etc.).

A good example is the [OBS](https://github.com/openSUSE/open-build-service/). Whenever an event happens, you can see it at  https://rabbit.opensuse.org/ or rather can listening directly on the message broker to receive events for further process.

Examples:

- user reserves a machine for the duration of 3d (as it could look like on the message bus):
```JSON
orthos.reservation
{
  "user": "Hans-Peter",
  "target_fqdn": "scooter.devel.example.com",
  "target_id": 3,
  "reason": "how much is the fish?",
  "until": "2020-10-11"
}
```
- user power-cycles a machine:
```JSON
orthos.power
{
  "user": "Dieter Bohlen",
  "target_fqdn": "modern.talking.example.com",
  "target_id": 6,
  "action": "restart"
}
```

With this we can get rid of Orthos task model approach mentioned at the beginning (https://github.com/openSUSE/orthos2/blob/master/orthos2/taskmanager/models.py) *and* we would gain more flexibility as people could now trigger custom tools/scripts whenever an event happens in Orthos. You could even think of querying Orthos API after an event happens in order to pull more information you may need.

Back in the days I came up with this own implementation of this task model stuff in Orthos2 as I was afraid of losing messages whenever the broker system gets stopped/restarted. According to the docs RabbitMQ is capable of storing queues/messages even if not running ("durable", https://www.rabbitmq.com/queues.html).

Having such notification system in place we don't lose anything instead we open Orthos2 for being easier involved in more complex environments.

**Comment by watologo1** [comment]
This would be quite some effort and is out of scope at least for now.

**Comment by SchoolGuy** [comment]
As good as this idea is, without Cobbler being able to do the same this makes little sense. As we will phase this project gradually out for a pure Cobbler deployment, implementing this doesn't make much sense. As such I will close this issue.
