### ISSUE TITLE
Production mode doesn't support serial console websocket

### ISSUE THREAD

**Issue by MingZhai** [openSUSE/orthos2#49]
Hi,
I found that I could run 'python manage.py serialconsole-ws --start' in development mode to setup serial console for machines. But in production mode(using nginx + uwsgi + django) there is no 'serialconsole' command.  After checking with "python manage.py help" command I found there is no '[frontend]    serialconsole-ws' option in production mode. 

Could you tell me how to add that? 

thanks a lot.

**Comment by MingZhai** [comment]
After I created a 'management/commands' folder under 'frontend/' folder, there is a new error: 'terminado' module needed! Run 'pip install terminado' ...

**Comment by MingZhai** [comment]
After I ran 'pip install terminado' to install it under /usr/lib/python3.6/site-packages/, serial console websocket starts to work.

**Comment by watologo1** [comment]
Good to know, python3-terminado then should certainly be added to the list of Requires: packges in the spec file.
Will do so on next submit...
