### ISSUE TITLE
Problem in taskmanager/executer.get_daily_tasks() due to timezone.now()

### ISSUE THREAD

**Issue by MingZhai** [openSUSE/orthos2#65]
Hi,
I have an orthos running instance and I enabled 'DailyCheckReservationExpirations' in dailytasks, expecting it run at 00:00. But I received around 30 times of notification emails that my machine will expire tomorrow instead of only once. I checked the source code of get_daily_tasks():
        **now = datetime.now()
        today = date.today()
        dailytasks = DailyTask.objects.filter(enabled=True).order_by('priority')
        for dailytask in dailytasks:
            if dailytask.executed_at.date() < today:
                if now.time() > ServerConfig.objects.get_daily_execution_time():
                    dailytask.executed_at = timezone.now()**

Function timezone.now() is 2 hours earlier than datetime.now() in timezone Berlin. That means when today increments(e.g 2021-05-01 00:00),  timezone.now() will still be '2021-04-30 22:00'. 

Therefore the same Dailytask 'DailyCheckReservationExpirations' will be repeated added to queue and executed until timezone.now() also reaches 2021-05-01. Therefore I received a lot of emails notifications until around 02:04 o'clock at night.

I will try to replace 'timezone.now()' with 'datetime.now()' to avoid 2 hours timezone issue. But I see already some warnings that 'RuntimeWarning: DateTimeField DailyTask.executed_at received a naive datetime (2021-04-30 10:46:40.042108) while time zone support is active.' .

Is it a problem? How is timezone really works in orthos?

Thanks a lot

Ming

**Comment by MingZhai** [comment]
Checked https://stackoverflow.com/questions/27517259/django-activate-not-showing-effect.  It looks that timezone.now() will always return UTC time regardless whether timezone is set or not in setting.py. Replace it with timezone.localtime(timezone.now()) should work. 

timezone.now is 2021-04-30 10:56:58.707273+00:00
timezone.localtime(timezone.now()) is 2021-04-30 14:04:19.710893+02:00

It looks that timezone.localtime(timezone.now()) will solve 2 hours difference issue

**Comment by watologo1** [comment]
Sounds sane. I won't have time for this today anymore.
I try to look deeper into this next week.
Thanks!

**Comment by MingZhai** [comment]
update:
This timezone.now() is not the only issue. I changed it to "timezone.localtime(timezone.now())" and check at 12 o'clock. DailyCheckReservationExpirations is still repeated executed. Hundreds of tasks are added to queue. Then I added some debug prints and found dailytask.save() doesn't update the value to database at 00:00 when today increments. Then I googled and found some hints that queryset are lazy (https://stackoverflow.com/questions/22980448/django-objects-filter-is-not-updating-field-but-objects-get-is     https://stackoverflow.com/questions/48832294/django-queryset-not-saving-changes-to-value). I changed code a little bit as following:
![image](https://user-images.githubusercontent.com/19308706/116810635-25c9b000-ab45-11eb-834e-e165fb13e7f8.png)

I saw new date is not saved to database successfully. Therefore the same task is added to queue repeatedly. 

But when I click 'Disable Task' ->'Enable Task' ->'Execute Now' buttons, The "DailyCheckReservationExpirations" task is executed exactly only once.
![image](https://user-images.githubusercontent.com/19308706/116811886-f36f8100-ab4b-11eb-88ea-c615c56cf5fa.png)

But I think the date is also not correct. Because the date I saw in taskmanager journals is 2021-04-30, not 05-01
![image](https://user-images.githubusercontent.com/19308706/116811920-23b71f80-ab4c-11eb-86b0-1c54c2296ebe.png)

**Comment by MingZhai** [comment]
Update:
I commented out send_email(user.email, subject, message) function from CheckReservationExpiration in notifications.py to avoid sending too many emails. And I changed 'tasks.daily.executiontime' from '00:00' to '09:30'. Now I see the Dailytask is executed only once.
![image](https://user-images.githubusercontent.com/19308706/116855391-96ca9f80-abf9-11eb-8229-e60bb6728fb0.png)
I have another local Virtualbox openSUSE machine and I also ran orthos using 'python manage.py runserver localhost:8000'. I also commented out the send_email function. I saw also that the Dailytask will be executed only once.

**Comment by MingZhai** [comment]
The flag "USE_TZ" in settings.py is "True". That means the time saved in database will always in UTC format, no matter how I save it as timezone.now() or timezone.localtime(timezone.now()). Therefore the 'dailytask.executed_at' read from database will always be UTC time. Am I understanding correct?
Besides I found the definition of "executed_at"
![image](https://user-images.githubusercontent.com/19308706/117536061-48ead880-aff9-11eb-8233-7ba1f4494d4c.png)
As default it uses "timezone.now", not "timezone.localtime". But I don't think changing it to "timezone.localtime" will solve the problem. Because "USE_TZ" is True. 
I can disable "USE_TZ" to 'False'. But there are many usages of timezone.xxxx() calls

**Comment by MingZhai** [comment]
Update. Issue is fixed.
Changed "if dailytask.executed_at.date() < today:" to "if timezone.localtime(dailytask.executed_at).date() < today:". 
Because anyway the saved and read-out time in database will always in UTC format, I convert UTC time to localtime during comparision. After that I receive expiration email for each machine only once at 00:00.
That means e.g. when local time is 10.05.2021 00:00:01, today date increments for 1 day, UTC time is still 09.05.2021 22:00:01. After converting it to localtime will it be also 10.05.2021 00:00:01. The other parts don't need to be changed.

**Comment by MingZhai** [comment]
Issue is fixed after converting the date format reading out from database from UTC to local time format explicitly
